# Generated by Django 4.1.1 on 2022-09-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0002_alter_student_age_alter_teacher_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=60)),
                ('article_text', models.TextField(default='')),
                ('article_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_application.teacher')),
            ],
        ),
    ]
